
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  dashboards:
    lovelace-svet:
      mode: yaml
      title: Освещение
      icon: mdi:lightbulb-group-outline
      show_in_sidebar: true
      filename: dashboards/svet.yaml
    lovelace-klimat:
      mode: yaml
      title: Климат
      icon: mdi:air-filter
      show_in_sidebar: true
      filename: dashboards/klimat.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
