substitutions:
  device_name: "Bedroom_brizer"
  friendly_name: "Bedroom Brizer"
esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"

esp8266:
  board: esp01_1m

#Здесь рассшифровка показания TVOC
text_sensor:
  - platform: template
    name: "TVOC Classification"
    id: tvoc_classification
    icon: "mdi:checkbox-marked-circle-outline"
    update_interval: never
    lambda: |-
      float tvoc = id(${device_name}_tvoc).state;
      if (isnan(tvoc)) {
        return {"unknown"};
      }
      int v = (int) tvoc;
      if (v <= 65) {
        return {"Воздух чистый"};
      }
      if (v <= 220) {
        return {"Рекомендуется проветрить"};
      }
      if (v <= 660) {
        return {"Рекомендуется усиленное проветривание"};
      }
      if (v <= 2200) {
        return {"Необходимо усиленное проветривание"};
      }
      if (v <= 3000) {
        return {"Умеренное загрязнение"};
      }
      if (v <= 4000) {
        return {"Сильное загрязнение"};
      }
      return {"Очень сильное загрязнение"};

logger:
  level: ERROR
  baud_rate: 0

api:
  encryption:
      key: x/1hOiYlafD5chqxcawNXgBZawnvRx4LespQjzlc+rs=

ota:
  - platform: esphome
    password: "Yuiop1975@"

wifi:
  ssid: "irv-very"
  password: "9265033203"

  ap:
    ssid: "Bedroom Brizer"
    password: "4K6fu6ciec03"

captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
  - platform: "tuya"
    name: "TVOC"
    id: "${device_name}_tvoc"
    sensor_datapoint: 7
    device_class: "volatile_organic_compounds"
    state_class: "measurement"
    accuracy_decimals: 0
    on_value:
      - component.update: tvoc_classification
  - platform: "tuya"
    name: "Outside Temperature"
    id: "${device_name}_temp"
    sensor_datapoint: 9
    unit_of_measurement: "°C"
  - platform: "tuya"
    name: "Air Quality"
    sensor_datapoint: 23
    icon: mdi:air-filter
  - platform: "tuya"
    name: "noname"
    sensor_datapoint: 18
switch:
  - platform: "tuya"
    name: "Power"
    switch_datapoint: 1
    id: "${device_name}_power_switch"
#если хочется чтобы при выключении, выключался и экран то можете раскомментировать строки внизу
#    on_turn_off:
#           then:
#            - switch.turn_off: "${device_name}_light_switch"
  - platform: "tuya"
    name: "Light"
    switch_datapoint: 4
    inverted: true
    id: "${device_name}_light_switch"
    icon: mdi:television-ambient-light
  - platform: "tuya"
    name: "Ionizer"
    switch_datapoint: 5
    icon: mdi:chart-bubble
  - platform: "tuya"
    name: "Filter Reset"
    id: "${device_name}_filter_reset"
    switch_datapoint: 103
    icon: mdi:calendar-filter
  - platform: "tuya"
    name: "13"
    switch_datapoint: 13

select:
  - platform: "tuya"
    name: "Mode"
    id: "${device_name}_mode"
    enum_datapoint: 2
    optimistic: true
    options:
      0: auto
      1: sleep
      2: manual
  - platform: "tuya"
    name: "Klapan"
    id: "${device_name}_klapan"
    enum_datapoint: 102
    optimistic: true
    options:
      0: Auto_1
      1: Auto_2
      2: Manual
number:
  - platform: tuya
    name: "Polojenie Zaslonki"
    id: "${device_name}_zaslonka"
    number_datapoint: 104
    min_value: 1
    max_value: 5
    step: 1
  - platform: tuya
    name: "Speed"
    id: "${device_name}_speed"
    number_datapoint: 101
    min_value: 1
    max_value: 9
    step: 1
